"""Report generators for the Battery Intelligence Platform.

Each generator consumes a :class:`ReportGenerationContext` — a snapshot of live
data already fetched by :class:`ReportService` through the existing
repositories. Generators never touch SQL and never call back into the API; they
only map the in-memory context into a :class:`ReportDocument`.

Shared layout logic lives on :class:`BaseReportGenerator` so that every report
type gets the mandated structure (title, generated timestamp, time range,
filters applied, summary, metrics, tables, chart placeholders, footer) without
duplicating code.
"""

from abc import ABC, abstractmethod
from datetime import datetime
from typing import Any, Dict, List
from uuid import uuid4

from app.models.report import (
    ReportDocument,
    ReportGenerationContext,
    ReportMetadata,
    ReportSection,
    ReportSectionType,
    ReportType,
    TimeRange,
)


class BaseReportGenerator(ABC):
    """Abstract base class for all report generators."""

    @abstractmethod
    def get_report_type(self) -> ReportType:
        """Return the report type this generator produces."""

    @abstractmethod
    async def generate(
        self, context: ReportGenerationContext, generated_by: str
    ) -> ReportDocument:
        """Generate a report document from the given live-data context."""

    # ------------------------------------------------------------------
    # Shared section/document builders (reused by every generator)
    # ------------------------------------------------------------------

    def _time_range(self, context: ReportGenerationContext) -> TimeRange:
        filters = context.filters
        return TimeRange(
            start=filters.date_from or datetime.min,
            end=filters.date_to or datetime.max,
        )

    def _metrics(
        self, section_id: str, title: str, rows: List[Dict[str, Any]]
    ) -> ReportSection:
        return ReportSection(
            id=section_id,
            type=ReportSectionType.METRICS,
            title=title,
            data={"metrics": rows},
        )

    def _table(
        self, section_id: str, title: str, rows: List[Dict[str, Any]]
    ) -> ReportSection:
        return ReportSection(
            id=section_id,
            type=ReportSectionType.TABLE,
            title=title,
            data={"rows": rows},
        )

    def _summary(self, section_id: str, title: str, text: str) -> ReportSection:
        return ReportSection(
            id=section_id,
            type=ReportSectionType.SUMMARY,
            title=title,
            data={"summary": text},
        )

    def _chart_placeholder(
        self, section_id: str, title: str, description: str
    ) -> ReportSection:
        return ReportSection(
            id=section_id,
            type=ReportSectionType.CHART,
            title=title,
            data={"placeholder": description},
        )

    def _document(
        self,
        context: ReportGenerationContext,
        title: str,
        report_type: ReportType,
        sections: List[ReportSection],
        generated_by: str,
    ) -> ReportDocument:
        return ReportDocument(
            id=str(uuid4()),
            title=title,
            report_type=report_type,
            generated_at=datetime.utcnow(),
            time_range=self._time_range(context),
            filters=context.filters,
            sections=sections,
            metadata=ReportMetadata(
                generated_by=generated_by,
                version="1.0",
                template_version="Phase 20",
            ),
        )

    def _base_sections(
        self, context: ReportGenerationContext, report_type: ReportType
    ) -> List[ReportSection]:
        """Leading sections every report must carry (filters + summary)."""
        return [
            self._summary(
                f"{report_type.value.lower().replace(' ', '-')}-filters",
                "Filters Applied",
                context.filters.summary(),
            )
        ]

    def _footer(
        self, context: ReportGenerationContext, report_type: ReportType
    ) -> ReportSection:
        return self._summary(
            f"{report_type.value.lower().replace(' ', '-')}-footer",
            "Report Footer",
            "Generated by Battery Intelligence Platform. " + context.filters.summary(),
        )

    def _machine_rows(self, context: ReportGenerationContext) -> List[Dict[str, Any]]:
        rows: List[Dict[str, Any]] = []
        for machine in context.machines:
            rows.append(
                {
                    "machine_id": machine.id,
                    "name": machine.name,
                    "status": machine.status,
                    "connection": machine.connection,
                    "health_score": machine.health_score,
                    "firmware": machine.firmware,
                    "last_seen": machine.last_seen.isoformat(),
                }
            )
        return rows

    def _ring_rows(self, context: ReportGenerationContext) -> List[Dict[str, Any]]:
        rows: List[Dict[str, Any]] = []
        for ring in context.rings:
            rows.append(
                {
                    "ring_id": ring.id,
                    "name": ring.name,
                    "status": ring.status,
                    "capacity_mwh": ring.capacity_mwh,
                    "installed_at": ring.installed_at.isoformat(),
                }
            )
        return rows

    def _timeline_rows(self, context: ReportGenerationContext) -> List[Dict[str, Any]]:
        rows: List[Dict[str, Any]] = []
        for event in context.timeline_events:
            rows.append(
                {
                    "event_id": event.id,
                    "timestamp": event.timestamp.isoformat(),
                    "type": event.type,
                    "machine_id": event.machine_id,
                    "message": event.message,
                }
            )
        return rows


class ExecutiveSummaryGenerator(BaseReportGenerator):
    def get_report_type(self) -> ReportType:
        return ReportType.EXECUTIVE_SUMMARY

    async def generate(
        self, context: ReportGenerationContext, generated_by: str
    ) -> ReportDocument:
        sections = self._base_sections(context, ReportType.EXECUTIVE_SUMMARY)
        sections.append(
            self._summary(
                "executive-summary-overview",
                "Executive Overview",
                (
                    f"{len(context.machines)} machine(s) tracked, "
                    f"{len(context.rings)} battery ring(s), "
                    f"{len(context.metrics)} metric(s) and "
                    f"{len(context.timeline_events)} timeline event(s) in the selected range."
                ),
            )
        )
        sections.append(
            self._metrics(
                "executive-summary-metrics",
                "Executive Summary Metrics",
                [
                    {"label": "Total Machines", "value": len(context.machines), "unit": "count"},
                    {
                        "label": "Active Machines",
                        "value": len([m for m in context.machines if m.status == "Healthy"]),
                        "unit": "count",
                    },
                    {"label": "Battery Rings", "value": len(context.rings), "unit": "count"},
                    {"label": "Timeline Events", "value": len(context.timeline_events), "unit": "count"},
                    {"label": "Tracked Metrics", "value": len(context.metrics), "unit": "count"},
                ],
            )
        )
        top = sorted(context.machines, key=lambda m: m.health_score, reverse=True)[:10]
        if top:
            sections.append(self._table("executive-summary-top-machines", "Top Machines by Health Score", self._machine_rows(context)[:10]))
        if context.rings:
            ring_summary: Dict[str, int] = {}
            for ring in context.rings:
                ring_summary[ring.name] = ring_summary.get(ring.name, 0) + 1
            sections.append(
                self._table(
                    "executive-summary-ring-summary",
                    "Ring Summary by Name",
                    [{"ring_name": name, "count": count} for name, count in sorted(ring_summary.items())],
                )
            )
        if context.timeline_events:
            sections.append(
                self._table(
                    "executive-summary-timeline",
                    "Recent Timeline Events",
                    self._timeline_rows(context)[:20],
                )
            )
        sections.append(
            self._chart_placeholder(
                "executive-summary-chart",
                "Health Score Trend",
                "Chart placeholder: fleet health score over the selected range.",
            )
        )
        sections.append(self._footer(context, ReportType.EXECUTIVE_SUMMARY))
        return self._document(
            context, "Executive Summary", ReportType.EXECUTIVE_SUMMARY, sections, generated_by
        )


class MachinePerformanceGenerator(BaseReportGenerator):
    def get_report_type(self) -> ReportType:
        return ReportType.MACHINE_PERFORMANCE

    async def generate(
        self, context: ReportGenerationContext, generated_by: str
    ) -> ReportDocument:
        sections = self._base_sections(context, ReportType.MACHINE_PERFORMANCE)

        machines = context.machines
        if context.filters.machines:
            machines = [m for m in machines if m.id in context.filters.machines]

        if not machines:
            sections.append(
                self._summary(
                    "machine-performance-no-data",
                    "No Machines Selected",
                    "No machines matched the selected filters. Adjust the machine filter and retry.",
                )
            )
        else:
            avg_health = sum(m.health_score for m in machines) / len(machines)
            sections.append(
                self._metrics(
                    "machine-performance-summary",
                    "Machine Performance Summary",
                    [
                        {"label": "Total Machines", "value": len(machines), "unit": "count"},
                        {"label": "Average Health Score", "value": round(avg_health, 1), "unit": "%"},
                        {
                            "label": "Healthy Machines",
                            "value": len([m for m in machines if m.status == "Healthy"]),
                            "unit": "count",
                        },
                        {
                            "label": "Critical Machines",
                            "value": len([m for m in machines if m.status == "Critical"]),
                            "unit": "count",
                        },
                    ],
                )
            )
            rows = [r for r in self._machine_rows(context) if r["machine_id"] in {m.id for m in machines}]
            sections.append(self._table("machine-performance-detailed", "Detailed Machine Information", rows))

            if context.rings and context.filters.rings:
                relevant = [r for r in context.rings if r.id in context.filters.rings]
                if relevant:
                    sections.append(self._table("machine-performance-rings", "Associated Battery Rings", [self._ring_row(r) for r in relevant]))

            sections.append(
                self._chart_placeholder(
                    "machine-performance-chart",
                    "Machine Performance Trend",
                    "Chart placeholder: uptime and health trend per machine.",
                )
            )
        sections.append(self._footer(context, ReportType.MACHINE_PERFORMANCE))
        return self._document(
            context, "Machine Performance", ReportType.MACHINE_PERFORMANCE, sections, generated_by
        )

    @staticmethod
    def _ring_row(ring: Any) -> Dict[str, Any]:
        return {
            "ring_id": ring.id,
            "name": ring.name,
            "status": ring.status,
            "capacity_mwh": ring.capacity_mwh,
            "installed_at": ring.installed_at.isoformat(),
        }


class BatterySummaryGenerator(BaseReportGenerator):
    def get_report_type(self) -> ReportType:
        return ReportType.BATTERY_SUMMARY

    async def generate(
        self, context: ReportGenerationContext, generated_by: str
    ) -> ReportDocument:
        sections = self._base_sections(context, ReportType.BATTERY_SUMMARY)

        rings = context.rings
        if context.filters.rings:
            rings = [r for r in rings if r.id in context.filters.rings]

        if not rings:
            sections.append(
                self._summary(
                    "battery-summary-no-data",
                    "No Batteries Selected",
                    "No battery rings matched the selected filters. Adjust the battery filter and retry.",
                )
            )
        else:
            status_counts: Dict[str, int] = {}
            for ring in rings:
                status_counts[ring.status] = status_counts.get(ring.status, 0) + 1
            sections.append(
                self._table(
                    "battery-summary-status",
                    "Battery Status Distribution",
                    [
                        {"status": status, "count": count, "percentage": round((count / len(rings)) * 100, 1)}
                        for status, count in sorted(status_counts.items())
                    ],
                )
            )
            total_capacity = sum(r.capacity_mwh for r in rings)
            sections.append(
                self._metrics(
                    "battery-summary-capacity",
                    "Capacity Summary",
                    [
                        {"label": "Total Capacity", "value": total_capacity, "unit": "MWh"},
                        {"label": "Average Capacity", "value": round(total_capacity / len(rings), 2), "unit": "MWh"},
                        {"label": "Occupied Slots", "value": len(rings), "unit": "count"},
                    ],
                )
            )
            sections.append(self._table("battery-summary-detailed", "Detailed Battery Information", self._ring_rows(context)))
        sections.append(self._footer(context, ReportType.BATTERY_SUMMARY))
        return self._document(
            context, "Battery Summary", ReportType.BATTERY_SUMMARY, sections, generated_by
        )


class BatteryLifecycleGenerator(BaseReportGenerator):
    def get_report_type(self) -> ReportType:
        return ReportType.BATTERY_LIFECYCLE

    async def generate(
        self, context: ReportGenerationContext, generated_by: str
    ) -> ReportDocument:
        sections = self._base_sections(context, ReportType.BATTERY_LIFECYCLE)

        sections.append(
            self._summary(
                "battery-lifecycle-overview",
                "Lifecycle Overview",
                (
                    f"Battery lifecycle derived from ring status ({len(context.rings)} ring(s)) "
                    f"and timeline milestones ({len(context.timeline_events)} event(s))."
                ),
            )
        )
        if context.rings:
            stage_counts: Dict[str, int] = {}
            for ring in context.rings:
                stage_counts[ring.status] = stage_counts.get(ring.status, 0) + 1
            sections.append(
                self._table(
                    "battery-lifecycle-stages",
                    "Current Lifecycle Stage by Ring",
                    [{"stage": stage, "ring_count": count} for stage, count in sorted(stage_counts.items())],
                )
            )
            sections.append(self._table("battery-lifecycle-inventory", "Battery Inventory", self._ring_rows(context)))
        if context.timeline_events:
            sections.append(
                self._table(
                    "battery-lifecycle-milestones",
                    "Lifecycle Milestones (Timeline Events)",
                    self._timeline_rows(context)[:50],
                )
            )
        else:
            sections.append(
                self._summary(
                    "battery-lifecycle-no-events",
                    "No Lifecycle Milestones",
                    "No timeline events are currently recorded for the selected range.",
                )
            )
        sections.append(
            self._chart_placeholder(
                "battery-lifecycle-chart",
                "Battery Lifecycle Distribution",
                "Chart placeholder: lifecycle stage distribution across the fleet.",
            )
        )
        sections.append(self._footer(context, ReportType.BATTERY_LIFECYCLE))
        return self._document(
            context, "Battery Lifecycle", ReportType.BATTERY_LIFECYCLE, sections, generated_by
        )


class QualitySummaryGenerator(BaseReportGenerator):
    def get_report_type(self) -> ReportType:
        return ReportType.QUALITY_SUMMARY

    async def generate(
        self, context: ReportGenerationContext, generated_by: str
    ) -> ReportDocument:
        sections = self._base_sections(context, ReportType.QUALITY_SUMMARY)

        quality = context.quality_data
        if not quality:
            sections.append(
                self._summary(
                    "quality-summary-no-data",
                    "No Quality Data",
                    "No quality summary rows are currently available from the collector.",
                )
            )
        else:
            sections.append(
                self._table(
                    "quality-summary-metrics",
                    "Quality Metrics",
                    [
                        {
                            "metric": row.metric,
                            "value": row.value,
                            "target": row.target,
                            "status": row.status,
                        }
                        for row in quality
                    ],
                )
            )
            met_target = sum(1 for row in quality if row.status == "Healthy")
            sections.append(
                self._metrics(
                    "quality-summary-kpis",
                    "Quality KPIs",
                    [
                        {"label": "Quality Metrics", "value": len(quality), "unit": "count"},
                        {"label": "Within Target", "value": met_target, "unit": "count"},
                        {"label": "Below Target", "value": len(quality) - met_target, "unit": "count"},
                    ],
                )
            )
            sections.append(
                self._table(
                    "quality-summary-machine-context",
                    "Machine Health Context",
                    [
                        {"machine": m.name, "status": m.status, "health_score": m.health_score}
                        for m in context.machines
                    ],
                )
            )
            sections.append(
                self._chart_placeholder(
                    "quality-summary-chart",
                    "Quality Trend",
                    "Chart placeholder: quality metric trend over the selected range.",
                )
            )
        sections.append(self._footer(context, ReportType.QUALITY_SUMMARY))
        return self._document(
            context, "Quality Summary", ReportType.QUALITY_SUMMARY, sections, generated_by
        )


class AnalyticsSummaryGenerator(BaseReportGenerator):
    def get_report_type(self) -> ReportType:
        return ReportType.ANALYTICS_SUMMARY

    async def generate(
        self, context: ReportGenerationContext, generated_by: str
    ) -> ReportDocument:
        sections = self._base_sections(context, ReportType.ANALYTICS_SUMMARY)

        analytics = context.analytics_data
        if not analytics:
            sections.append(
                self._summary(
                    "analytics-summary-no-data",
                    "No Analytics Data",
                    "No analytics summary rows are currently available from the collector.",
                )
            )
        else:
            sections.append(
                self._table(
                    "analytics-summary-kpis",
                    "Analytics KPIs",
                    [
                        {"key": row.key, "label": row.label, "value": row.value, "unit": row.unit}
                        for row in analytics
                    ],
                )
            )
        metrics = context.metrics
        if metrics:
            sections.append(
                self._table(
                    "analytics-summary-metrics",
                    "Metric Detail",
                    [
                        {"id": m.id, "name": m.name, "value": m.value, "unit": m.unit, "status": m.status}
                        for m in metrics
                    ],
                )
            )
        sections.append(
            self._metrics(
                "analytics-summary-overview",
                "Analytics Overview",
                [
                    {"label": "Analytics KPIs", "value": len(analytics), "unit": "count"},
                    {"label": "Metrics Received", "value": len(metrics), "unit": "count"},
                ],
            )
        )
        sections.append(
            self._chart_placeholder(
                "analytics-summary-chart",
                "Performance Trend",
                "Chart placeholder: metric trends across the selected range.",
            )
        )
        sections.append(self._footer(context, ReportType.ANALYTICS_SUMMARY))
        return self._document(
            context, "Analytics Summary", ReportType.ANALYTICS_SUMMARY, sections, generated_by
        )


class TimelineReportGenerator(BaseReportGenerator):
    def get_report_type(self) -> ReportType:
        return ReportType.TIMELINE_REPORT

    async def generate(
        self, context: ReportGenerationContext, generated_by: str
    ) -> ReportDocument:
        sections = self._base_sections(context, ReportType.TIMELINE_REPORT)

        events = context.timeline_events
        if context.filters.timeline_events:
            wanted = set(context.filters.timeline_events)
            events = [e for e in events if e.type in wanted]

        sections.append(
            self._metrics(
                "timeline-report-kpis",
                "Timeline Report",
                [
                    {"label": "Events", "value": len(events), "unit": "count"},
                    {"label": "Machines", "value": len({e.machine_id for e in events}), "unit": "count"},
                    {"label": "Event Types", "value": len({e.type for e in events}), "unit": "count"},
                ],
            )
        )
        if events:
            by_type: Dict[str, int] = {}
            for event in events:
                by_type[event.type] = by_type.get(event.type, 0) + 1
            sections.append(
                self._table(
                    "timeline-report-by-type",
                    "Events by Type",
                    [{"event_type": etype, "count": count} for etype, count in sorted(by_type.items())],
                )
            )
            sections.append(
                self._table(
                    "timeline-report-events",
                    "Timeline Events",
                    [r for r in self._timeline_rows(context) if r["event_id"] in {e.id for e in events}],
                )
            )
        else:
            sections.append(
                self._summary(
                    "timeline-report-no-events",
                    "No Timeline Events",
                    "No timeline events were recorded for the selected range and filters.",
                )
            )
        sections.append(
            self._chart_placeholder(
                "timeline-report-chart",
                "Events Over Time",
                "Chart placeholder: event volume over the selected range.",
            )
        )
        sections.append(self._footer(context, ReportType.TIMELINE_REPORT))
        return self._document(
            context, "Timeline Report", ReportType.TIMELINE_REPORT, sections, generated_by
        )


class OperationsSummaryGenerator(BaseReportGenerator):
    def get_report_type(self) -> ReportType:
        return ReportType.OPERATIONS_SUMMARY

    async def generate(
        self, context: ReportGenerationContext, generated_by: str
    ) -> ReportDocument:
        sections = self._base_sections(context, ReportType.OPERATIONS_SUMMARY)

        machines = context.machines
        if context.filters.machines:
            machines = [m for m in machines if m.id in context.filters.machines]

        status_dist: Dict[str, int] = {}
        for machine in machines:
            status_dist[machine.status] = status_dist.get(machine.status, 0) + 1

        sections.append(
            self._metrics(
                "operations-summary-fleet",
                "Fleet Operations",
                [
                    {"label": "Machines", "value": len(machines), "unit": "count"},
                    {"label": "Rings", "value": len(context.rings), "unit": "count"},
                    {"label": "Events", "value": len(context.timeline_events), "unit": "count"},
                    {"label": "Healthy Machines", "value": status_dist.get("Healthy", 0), "unit": "count"},
                ],
            )
        )
        if machines:
            sections.append(
                self._table(
                    "operations-summary-machine-status",
                    "Machine Status",
                    [{"status": status, "count": count} for status, count in sorted(status_dist.items())],
                )
            )
            sections.append(self._table("operations-summary-machines", "Machines", self._machine_rows(context)))
        else:
            sections.append(
                self._summary(
                    "operations-summary-no-data",
                    "No Operational Data",
                    "No machine data matched the selected filters.",
                )
            )
        if context.timeline_events:
            sections.append(
                self._table(
                    "operations-summary-recent-events",
                    "Recent Operational Events",
                    self._timeline_rows(context)[:20],
                )
            )
        sections.append(
            self._chart_placeholder(
                "operations-summary-chart",
                "Operational Load",
                "Chart placeholder: operational load and fleet status over the selected range.",
            )
        )
        sections.append(self._footer(context, ReportType.OPERATIONS_SUMMARY))
        return self._document(
            context, "Operations Summary", ReportType.OPERATIONS_SUMMARY, sections, generated_by
        )


class SystemHealthGenerator(BaseReportGenerator):
    def get_report_type(self) -> ReportType:
        return ReportType.SYSTEM_HEALTH

    async def generate(
        self, context: ReportGenerationContext, generated_by: str
    ) -> ReportDocument:
        sections = self._base_sections(context, ReportType.SYSTEM_HEALTH)

        health = context.health
        if health:
            sections.append(
                self._summary(
                    "system-health-status",
                    "System Status",
                    (
                        f"Battery Intelligence Platform API is {health.status}. "
                        f"Service: {health.service}. Version: {health.version}. "
                        f"Environment: {health.environment}."
                        if hasattr(health, "service")
                        else f"System status: {health.status}."
                    ),
                )
            )
            sections.append(
                self._metrics(
                    "system-health-details",
                    "System Health",
                    [
                        {"label": "API Status", "value": health.status, "unit": ""},
                        {"label": "Environment", "value": health.environment, "unit": ""},
                        {"label": "API Version", "value": health.version, "unit": ""},
                        {"label": "Machines Tracked", "value": len(context.machines), "unit": "count"},
                    ],
                )
            )
        else:
            sections.append(
                self._summary(
                    "system-health-unavailable",
                    "Health Data Unavailable",
                    "The platform health endpoint returned no data for this run.",
                )
            )
        metric_status: Dict[str, int] = {}
        for metric in context.metrics:
            metric_status[metric.status] = metric_status.get(metric.status, 0) + 1
        if context.metrics:
            sections.append(
                self._table(
                    "system-health-metric-status",
                    "Metric Status",
                    [{"status": status, "count": count} for status, count in sorted(metric_status.items())],
                )
            )
        sections.append(
            self._chart_placeholder(
                "system-health-chart",
                "Service Health",
                "Chart placeholder: API and collector health over the selected range.",
            )
        )
        sections.append(self._footer(context, ReportType.SYSTEM_HEALTH))
        return self._document(
            context, "System Health", ReportType.SYSTEM_HEALTH, sections, generated_by
        )


class CollectorStatusGenerator(BaseReportGenerator):
    """Reports on collector freshness.

    Collector health is inferred from the freshness of machine heartbeats
    (``last_seen``) relative to the platform freshness window.
    """

    def get_report_type(self) -> ReportType:
        return ReportType.COLLECTOR_STATUS

    async def generate(
        self, context: ReportGenerationContext, generated_by: str
    ) -> ReportDocument:
        sections = self._base_sections(context, ReportType.COLLECTOR_STATUS)

        from datetime import datetime, timezone

        now = datetime.now(timezone.utc)
        fresh_machines: List[Dict[str, Any]] = []
        stale_machines: List[Dict[str, Any]] = []
        for machine in context.machines:
            last_seen = machine.last_seen
            if last_seen is not None and last_seen.tzinfo is None:
                last_seen = last_seen.replace(tzinfo=timezone.utc)
            delta_seconds = (now - last_seen).total_seconds() if last_seen is not None else None
            row = {
                "machine_id": machine.id,
                "name": machine.name,
                "last_seen": machine.last_seen.isoformat() if machine.last_seen else "never",
                "age_seconds": delta_seconds,
            }
            if delta_seconds is not None and delta_seconds <= 60:
                fresh_machines.append(row)
            else:
                stale_machines.append(row)

        sections.append(
            self._metrics(
                "collector-status-summary",
                "Collector Status",
                [
                    {"label": "Machines Reporting", "value": len(fresh_machines), "unit": "count"},
                    {"label": "Machines Stale", "value": len(stale_machines), "unit": "count"},
                    {"label": "Timeline Events", "value": len(context.timeline_events), "unit": "count"},
                ],
            )
        )
        if context.machines:
            sections.append(
                self._table(
                    "collector-status-fresh",
                    "Machines Reporting (last 60s)",
                    [r for r in self._machine_rows(context) if r["machine_id"] in {m["machine_id"] for m in fresh_machines}],
                )
            )
            if stale_machines:
                sections.append(
                    self._table(
                        "collector-status-stale",
                        "Machines Not Reporting",
                        [r for r in self._machine_rows(context) if r["machine_id"] in {m["machine_id"] for m in stale_machines}],
                    )
                )
        else:
            sections.append(
                self._summary(
                    "collector-status-no-data",
                    "No Collector Data",
                    "No machine heartbeats are currently available from the collector.",
                )
            )
        sections.append(
            self._chart_placeholder(
                "collector-status-chart",
                "Collector Heartbeats",
                "Chart placeholder: collector heartbeat recency over the selected range.",
            )
        )
        sections.append(self._footer(context, ReportType.COLLECTOR_STATUS))
        return self._document(
            context, "Collector Status", ReportType.COLLECTOR_STATUS, sections, generated_by
        )


# Registry for report generators                                          # noqa: E266
class ReportGeneratorRegistry:
    """Registry mapping every supported report type to its generator."""

    def __init__(self) -> None:
        self._generators: Dict[ReportType, BaseReportGenerator] = {}

    def register(self, generator: BaseReportGenerator) -> None:
        self._generators[generator.get_report_type()] = generator

    def get_generator(self, report_type: ReportType) -> BaseReportGenerator:
        if report_type not in self._generators:
            raise ValueError(f"No generator registered for report type: {report_type}")
        return self._generators[report_type]

    def get_supported_types(self) -> List[ReportType]:
        return list(self._generators.keys())

    @staticmethod
    def create_default_registry() -> "ReportGeneratorRegistry":
        registry = ReportGeneratorRegistry()
        for generator in [
            ExecutiveSummaryGenerator(),
            MachinePerformanceGenerator(),
            BatterySummaryGenerator(),
            BatteryLifecycleGenerator(),
            QualitySummaryGenerator(),
            AnalyticsSummaryGenerator(),
            TimelineReportGenerator(),
            OperationsSummaryGenerator(),
            SystemHealthGenerator(),
            CollectorStatusGenerator(),
        ]:
            registry.register(generator)
        return registry